services:
  server:
    image: vinaedu-server
    env_file:
      - .env.prod
    ports:
      - '80:3000'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    command: sh -c "yarn start:prod"

  face-recognition:
    image: face-recognition
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    command: sh -c "gunicorn -w 2 -b 0.0.0.0:8000 app:app"
    
    